import type { ForumThread, ForumComment } from '@/shared/types/database'

const ago = (n: number) => new Date(Date.now() - n * 3600_000).toISOString()

export const demoForumDb = {
  threads: [
    {
      id: 't-monster',
      faculty_id: 'ingenieria',
      author_id: 'demo-otro',
      author_name: 'Cata M.',
      title: '¿Alguien sabe si el laboratorio de computación está abierto hoy?',
      content: 'Hola, necesito hacer un trabajo para Inteligencia Artificial y quería saber si los laboratorios del edificio Ejército 441 están abiertos los sábados.',
      tags: ['Duda', 'Computación'],
      votes_up: 5,
      votes_down: 0,
      is_pinned: true,
      is_official: false,
      created_at: ago(24),
      updated_at: ago(24),
    },
    {
      id: 't-feria',
      faculty_id: 'ingenieria',
      author_id: 'demo-otro',
      author_name: 'Seba R.',
      title: 'Feria de Proyectos de Título 2026',
      content: 'Este martes 14 se realizará la feria anual en el patio central. Vengan a ver los proyectos y a comer algo de las actividades del Centro de Alumnos.',
      tags: ['Anuncio', 'Feria'],
      votes_up: 12,
      votes_down: 1,
      is_pinned: false,
      is_official: false,
      created_at: ago(6),
      updated_at: ago(6),
    },
    {
      id: 't-derecho',
      faculty_id: 'derecho',
      author_id: 'demo-otro',
      author_name: 'Diego P.',
      title: 'Apuntes para Derecho Constitucional',
      content: 'Hola a todos, les dejo un link con mis apuntes del semestre pasado para el examen con el profesor Gómez. ¡Espero que les sirva!',
      tags: ['Compartir', 'Apuntes'],
      votes_up: 8,
      votes_down: 0,
      is_pinned: false,
      is_official: false,
      created_at: ago(48),
      updated_at: ago(48),
    },
    {
      id: 't-general-1',
      faculty_id: null,
      author_id: 'demo-otro',
      author_name: 'Felipe A.',
      title: '¡Bienvenidos al nuevo foro de UDP Map!',
      content: 'Este es el tablón general de anuncios de la universidad. Recuerden mantener el respeto y usar las categorías correspondientes para sus facultades.',
      tags: ['Anuncio', 'UDP'],
      votes_up: 25,
      votes_down: 0,
      is_pinned: true,
      is_official: false,
      created_at: ago(72),
      updated_at: ago(72),
    }
  ] as ForumThread[],
  comments: [
    {
      id: 'c-1',
      thread_id: 't-monster',
      parent_comment_id: null,
      author_id: 'demo-otro',
      author_name: 'Andrés L.',
      content: 'Sí, Ejército 441 abre los sábados hasta las 14:00 hrs.',
      created_at: ago(22),
    },
    {
      id: 'c-2',
      thread_id: 't-monster',
      parent_comment_id: 'c-1',
      author_id: 'demo-otro',
      author_name: 'Cata M.',
      content: '¡Buenísima, muchas gracias por confirmar!',
      created_at: ago(21),
    },
    {
      id: 'c-3',
      thread_id: 't-monster',
      parent_comment_id: null,
      author_id: 'demo-otro',
      author_name: 'Carla J.',
      content: 'Ojo que a veces cierran antes si no hay nadie. Te recomiendo llegar temprano.',
      created_at: ago(20),
    }
  ] as ForumComment[],
  votes: new Map<string, Map<string, 1 | -1>>(), // threadId -> (userId -> value)
}
